#! /bin/sh

set -e

case "$1" in

	-h|--help)

		echo "${0##*/}: Generate AppImages."
		echo "Usage: ${0##*/} [-h|--help] <entry-point>"
		exit

	;;

esac

_e () {
	echo -e "${0##*/}: \e[31mError:\e[0m $@" >&2
	exit 1
}


# -- Functions.

APPDIR=$(mktemp -d)


# --
