#! /bin/sh

set -e

case "$1" in

	-h|--help)

		echo "${0##*/}: Copy binaries and their dependencies to a directory."
		echo "Usage: ${0##*/} [-h|--help] <directory> <binaries>"
		exit

	;;

esac

_e () { echo -e "${0##*/}: \e[31mError:\e[0m $@" >&2; exit 1; }


#	Check the command line.

test $# -lt 2 &&
	_e "Too few arguments."


#	Copy the binaries.

dst="$1"
shift

for item in "$@"; do
	test -f "$item" ||
		_e "'$item' is not a file."

	mkdir -p $dst/${item%/*}
	cp -u $item $dst/$item
done


#	Copy the libraries. (Oh, if we had static binaries everywhere!)

ldd "$@"        |
cut -d ' ' -f 3 |
sed '/:$/d'     |
sort -u         |
while read lib; do
	mkdir -p $dst/${lib%/*}
	cp -u $lib $dst/$lib
done
