#! /bin/sh

set -e

case $1 in

	-h|--help)

		echo "copier: Copy a binary and its dependencies to a directory."
		echo "Usage: ${0##*/} [-h|--help] <binary> <directory>"
		exit

	;;

esac

_e () { printf %b "${0##*/}: \e[31mError:\e[0m $@\n" >&2; exit 1; }


# -- Check if the paths are valid.

[ $# -ne 2 ] &&
	_e "Wrong number of arguments."

[ -f $(which "$1") ] ||
	_e "'$1' does not exist."

mkdir -p $2


# -- Copy the binary.

b=$(which "$1")

[ -f "$1" ] && {
	mkdir -p $2/bin
	cp $b $2/bin/${b##*/}
} || {
	mkdir -p $2/${b%/*}
	cp $b $2/$b
}


# -- Get the library dependencies.

libs=$(ldd $b | awk 'BEGIN { ORS=" " } $1 ~/^\//{ print $1 } $3~/^\//{ print $3 }' | sed 's/,$/\n/')


# -- Copy the dependencies.

for l in $libs; do
	mkdir -p $2/${l%/*}
	cp -u $l $2/$l
done
