#! /bin/sh


set -e
_e () { printf "${0##*/}: \e[31mError:\e[0m %s\n" "$*" >&2; exit 1; }


case "$1" in
	-h|--help)
		printf "%s\n" \
			"${0##*/}: print the external commands called by a UNIX shell script." \
			"" \
			"usage:" \
			"  ${0##*/} [-h|--help]" \
			"  ${0##*/} <script>"
		exit
	;;
esac


#	functions.

_list_cmds () {
	sed \
		-e '/^#/d' \
		-e '/^$/d' \
		-e 's:^[ \t]*::' \
		-e 's:(:\n:g' \
		-e 's:{:\n:g' \
		-e 's:`:\n:g' \
		-e 's:|:\n:g' \
		-e 's:&:\n:g' \
		-e 's:;:\n:g' \
		"$@"
}


_get_path () {
	while read f; do
		{
			which -- "$f" && continue
			test -f "$f" && printf "%s\n" "$f"
		} || true
	done 2> /dev/null
}


#	get the list.

_list_cmds "$@" |
	cut -d ' ' -f 1 |
	sort -u         |
	_get_path
