#! /bin/sh

set -e

case "$1" in

	-h|--help)

		echo "execs: Print the executable files found in a script."
		echo "Usage: ${0##*/} [-h|--help] <binary>"
		exit

	;;

esac

_e () { printf %b "${0##*/}: \e[31mError:\e[0m $@\n" >&2; exit 1; }

[ -f $1 ] &&
	from="$1" ||
	from=/dev/stdin

# -- Binaries match the following rules:
# -- They are the first word in a line.
# -- They come after a "`" character.
# -- They come after a "|" character.
# -- They come after a "$(" construct.
# -- Their names start with "/", "./" or "../".

bins=$(awk '{ for (i = 1; i <= NF; i++) { print $i } }' $from | sort | uniq | sed 's/\$(//g; s/`//g; /^#/d; /^-/d; /^+/d; s/\$.[a-zA-Z0-9].*//g; /^$/d;')

for x in $bins; do
	readlink -f $(which - "$x")
done 2> /dev/null
